In [ ]:
### If you need to install matplotlib uncomment the following line and run this code block.
# !pip install matplotlib

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
variants = pd.read_csv("Input_data/variant_cases.csv", sep=",", index_col=0)
vaccinations = pd.read_csv("Input_data/vaccinations.csv", sep=',', index_col=0)

In [3]:
def drop_data(row):
    date = row["year_week"].split("-")
    if int(date[0]) == 2020:
        if int(date[1]) < 40:
            return "drop"

In [4]:
variants = variants.loc[(variants['variant'] == 'B.1.617.2') | (variants['variant'] == 'B.1.1.529') |\
                       (variants['variant'] == 'B.1.1.7') | (variants['variant'] == 'B.1.351')]
variants["drop_column"] = variants.apply(drop_data, axis = 1)
variants = variants.loc[variants["drop_column"] != "drop"]
variants = variants.drop(columns = "drop_column")
variants

,country_code,year_week,source,new_cases,number_sequenced,percent_cases_sequenced,valid_denominator,variant,number_detections_variant,number_sequenced_known_variant,percent_variant
country,,,,,,,,,,,
Austria,AT,2020-40,GISAID,5597,4,0.1,True,B.1.1.529,0,4.0,0.0
Austria,AT,2020-40,GISAID,5597,4,0.1,True,B.1.1.7,0,4.0,0.0
Austria,AT,2020-40,GISAID,5597,4,0.1,True,B.1.351,0,4.0,0.0
Austria,AT,2020-40,GISAID,5597,4,0.1,True,B.1.617.2,0,4.0,0.0
Austria,AT,2020-41,GISAID,7486,26,0.3,True,B.1.1.529,0,26.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
Sweden,SE,2022-08,TESSy,17642,3327,18.9,True,B.1.1.529,3324,3327.0,99.9
Sweden,SE,2022-08,TESSy,17642,3327,18.9,True,B.1.617.2,3,3327.0,0.1
Sweden,SE,2022-09,TESSy,12532,2572,20.5,True,B.1.1.529,2561,2572.0,99.6
Sweden,SE,2022-09,TESSy,12532,2572,20.5,True,B.1.617.2,11,2572.0,0.4
Sweden,SE,2022-10,TESSy,10106,1648,16.3,True,B.1.1.529,1648,1648.0,100.0

In [5]:
sort_variants = variants.sort_values('number_sequenced')
var = sort_variants.drop_duplicates(subset=['country_code', 'year_week', 'variant'], keep='last')
variants = var.sort_values(by=['country_code','year_week'])
variants

,country_code,year_week,source,new_cases,number_sequenced,percent_cases_sequenced,valid_denominator,variant,number_detections_variant,number_sequenced_known_variant,percent_variant
country,,,,,,,,,,,
Austria,AT,2020-40,GISAID,5597,4,0.1,True,B.1.1.529,0,4.0,0.0
Austria,AT,2020-40,GISAID,5597,4,0.1,True,B.1.1.7,0,4.0,0.0
Austria,AT,2020-40,GISAID,5597,4,0.1,True,B.1.351,0,4.0,0.0
Austria,AT,2020-40,GISAID,5597,4,0.1,True,B.1.617.2,0,4.0,0.0
Austria,AT,2020-41,GISAID,7486,26,0.3,True,B.1.1.529,0,26.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
Slovakia,SK,2022-09,TESSy,75031,428,0.6,True,B.1.1.529,427,428.0,99.8
Slovakia,SK,2022-10,GISAID,71256,1,0.0,True,B.1.1.7,0,1.0,0.0
Slovakia,SK,2022-10,GISAID,71256,1,0.0,True,B.1.351,0,1.0,0.0
Slovakia,SK,2022-10,GISAID,71256,1,0.0,True,B.1.617.2,0,1.0,0.0
Slovakia,SK,2022-10,TESSy,71256,269,0.4,True,B.1.1.529,269,269.0,100.0

In [6]:
def get_variants(row):
    percentage = row['percent_variant']/100
    cases = row['new_cases'] * percentage
    return cases
    
variants['number_cases_ratio'] = variants.apply(get_variants, axis=1)
variants = variants.drop(columns=['source', 'number_sequenced', 'percent_cases_sequenced', 'valid_denominator',\
                                  'number_detections_variant', 'number_sequenced_known_variant'])
variants

,country_code,year_week,new_cases,variant,percent_variant,number_cases_ratio
country,,,,,,
Austria,AT,2020-40,5597,B.1.1.529,0.0,0.000
Austria,AT,2020-40,5597,B.1.1.7,0.0,0.000
Austria,AT,2020-40,5597,B.1.351,0.0,0.000
Austria,AT,2020-40,5597,B.1.617.2,0.0,0.000
Austria,AT,2020-41,7486,B.1.1.529,0.0,0.000
...,...,...,...,...,...,...
Slovakia,SK,2022-09,75031,B.1.1.529,99.8,74880.938
Slovakia,SK,2022-10,71256,B.1.1.7,0.0,0.000
Slovakia,SK,2022-10,71256,B.1.351,0.0,0.000
Slovakia,SK,2022-10,71256,B.1.617.2,0.0,0.000
Slovakia,SK,2022-10,71256,B.1.1.529,100.0,71256.000

In [7]:
variants = variants.loc[(variants['variant'] != 'B.1.351')]
variants

,country_code,year_week,new_cases,variant,percent_variant,number_cases_ratio
country,,,,,,
Austria,AT,2020-40,5597,B.1.1.529,0.0,0.000
Austria,AT,2020-40,5597,B.1.1.7,0.0,0.000
Austria,AT,2020-40,5597,B.1.617.2,0.0,0.000
Austria,AT,2020-41,7486,B.1.1.529,0.0,0.000
Austria,AT,2020-41,7486,B.1.1.7,0.0,0.000
...,...,...,...,...,...,...
Slovakia,SK,2022-09,75031,B.1.617.2,0.2,150.062
Slovakia,SK,2022-09,75031,B.1.1.529,99.8,74880.938
Slovakia,SK,2022-10,71256,B.1.1.7,0.0,0.000
Slovakia,SK,2022-10,71256,B.1.617.2,0.0,0.000
Slovakia,SK,2022-10,71256,B.1.1.529,100.0,71256.000

In [8]:
vaccinations = vaccinations.loc[vaccinations['TargetGroup'] == 'ALL']
vaccinations = vaccinations.drop_duplicates(subset='ReportingCountry')
vaccinations

,ReportingCountry,Denominator,NumberDosesReceived,NumberDosesExported,FirstDose,FirstDoseRefused,SecondDose,DoseAdditional1,UnknownDose,Region,TargetGroup,Vaccine,Population
YearWeekISO,,,,,,,,,,,,,
2020-W53,AT,8901064.0,61425.0,0.0,5314,NaN,0,0,0,AT,ALL,COM,8901064
2020-W53,BE,11522440.0,0.0,NaN,0,NaN,0,0,0,BE,ALL,MOD,11522440
2020-W52,BG,6951482.0,10725.0,NaN,0,NaN,0,0,0,BG,ALL,COM,6951482
2020-W52,CY,888005.0,9750.0,NaN,369,NaN,0,0,0,CY,ALL,COM,888005
2020-W52,CZ,10693939.0,11700.0,0.0,1268,NaN,0,0,0,CZ,ALL,COM,10693939
2020-W52,DE,83166711.0,151125.0,0.0,24347,NaN,19,0,0,DE,ALL,COM,83166711
2020-W50,DK,5822763.0,0.0,0.0,2,NaN,0,0,0,DK,ALL,COM,5822763
2020-W52,EE,1328976.0,9750.0,0.0,191,NaN,3,0,0,EE,ALL,COM,1328976
2020-W52,EL,10718565.0,0.0,0.0,0,NaN,0,0,0,EL,ALL,NVXD,10718565
2020-W53,ES,47332614.0,382200.0,NaN,96367,NaN,0,0,0,ES,ALL,COM,47332614
2020-W52,FI,NaN,NaN,NaN,0,NaN,0,0,0,FI1D2,ALL,COM,5525292
2020-W53,FR,NaN,NaN,NaN,3,NaN,0,0,0,FRM,ALL,UNK,67320216
2020-W52,HR,4058165.0,NaN,NaN,54,NaN,10,0,0,HR,ALL,UNK,4058165
2020-W52,HU,9769526.0,9750.0,NaN,1095,NaN,0,0,0,HU,ALL,COM,9769526
2020-W52,IE,4964440.0,9750.0,0.0,0,NaN,0,0,0,IE,ALL,COM,4964440
2020-W53,IS,364134.0,11700.0,0.0,4943,NaN,0,0,0,IS,ALL,COM,364134
2020-W52,IT,1293941.0,NaN,NaN,38,NaN,0,0,0,ITF1,ALL,COM,59641488
2021-W01,LI,38747.0,0.0,0.0,4,NaN,0,0,0,LI,ALL,COM,38747
2020-W52,LT,1973579.0,6795.0,NaN,1709,NaN,0,0,0,LT02,ALL,COM,2794090
2020-W52,LU,626108.0,9750.0,NaN,0,NaN,0,0,0,LU,ALL,COM,626108
2020-W52,LV,1907675.0,9750.0,NaN,0,NaN,0,0,0,LV,ALL,COM,1907675
2020-W52,MT,514564.0,NaN,NaN,57,NaN,0,0,0,MT,ALL,COM,514564
2020-W52,NL,17407585.0,0.0,0.0,0,NaN,0,0,0,NL,ALL,NVXD,17407585
2020-W52,NO,5367580.0,9750.0,NaN,68,NaN,0,0,0,NO,ALL,COM,5367580
2020-W52,PL,2864809.0,NaN,NaN,0,NaN,0,0,0,PL51,ALL,MOD,37958138
2020-W52,PT,10295909.0,9750.0,NaN,5148,NaN,1,0,1,PT,ALL,COM,10295909
2021-W04,RO,19328838.0,926370.0,NaN,586514,0.0,106470,0,0,RO,ALL,COM,19328838
2020-W52,SE,376157.0,NaN,NaN,0,NaN,0,0,0,SE32,ALL,NVXD,10327589
2020-W52,SI,2095861.0,11700.0,NaN,4896,NaN,0,0,0,SI,ALL,COM,2095861
2020-W52,SK,5457873.0,9750.0,0.0,0,NaN,0,0,0,SK,ALL,COM,5457873

In [9]:
def get_population(row, df):
    pop = df['Population'].loc[df['ReportingCountry'] == row['country_code']]
    return pop[0]

variants['population'] = variants.apply(lambda row: get_population(row,vaccinations), axis=1)
variants

,country_code,year_week,new_cases,variant,percent_variant,number_cases_ratio,population
country,,,,,,,
Austria,AT,2020-40,5597,B.1.1.529,0.0,0.000,8901064
Austria,AT,2020-40,5597,B.1.1.7,0.0,0.000,8901064
Austria,AT,2020-40,5597,B.1.617.2,0.0,0.000,8901064
Austria,AT,2020-41,7486,B.1.1.529,0.0,0.000,8901064
Austria,AT,2020-41,7486,B.1.1.7,0.0,0.000,8901064
...,...,...,...,...,...,...,...
Slovakia,SK,2022-09,75031,B.1.617.2,0.2,150.062,5457873
Slovakia,SK,2022-09,75031,B.1.1.529,99.8,74880.938,5457873
Slovakia,SK,2022-10,71256,B.1.1.7,0.0,0.000,5457873
Slovakia,SK,2022-10,71256,B.1.617.2,0.0,0.000,5457873
Slovakia,SK,2022-10,71256,B.1.1.529,100.0,71256.000,5457873

In [10]:
def normalize_counts(row):
    percentage = (row['number_cases_ratio']/row['population']) * 100000
    return percentage
    
variants['normalized_counts'] = variants.apply(normalize_counts, axis=1)

variants = variants.reset_index()
variants

,country,country_code,year_week,new_cases,variant,percent_variant,number_cases_ratio,population,normalized_counts
0,Austria,AT,2020-40,5597,B.1.1.529,0.0,0.000,8901064,0.000000
1,Austria,AT,2020-40,5597,B.1.1.7,0.0,0.000,8901064,0.000000
2,Austria,AT,2020-40,5597,B.1.617.2,0.0,0.000,8901064,0.000000
3,Austria,AT,2020-41,7486,B.1.1.529,0.0,0.000,8901064,0.000000
4,Austria,AT,2020-41,7486,B.1.1.7,0.0,0.000,8901064,0.000000
...,...,...,...,...,...,...,...,...,...
6835,Slovakia,SK,2022-09,75031,B.1.617.2,0.2,150.062,5457873,2.749459
6836,Slovakia,SK,2022-09,75031,B.1.1.529,99.8,74880.938,5457873,1371.980220
6837,Slovakia,SK,2022-10,71256,B.1.1.7,0.0,0.000,5457873,0.000000
6838,Slovakia,SK,2022-10,71256,B.1.617.2,0.0,0.000,5457873,0.000000
6839,Slovakia,SK,2022-10,71256,B.1.1.529,100.0,71256.000,5457873,1305.563541

In [11]:
variant_data = variants[["variant","normalized_counts"]]#.reset_index(drop=True)
variant_data_p = variant_data.pivot(columns = ["variant"], values = ["normalized_counts"])
variant_data_p = variant_data_p.droplevel(level = 0, axis = 1)
week_data = pd.DataFrame(variants[["country","country_code","year_week","new_cases","population"]]).reset_index(drop=True)
week_data.index.rename("variant", inplace = True)
combined = week_data.join(variant_data_p, on="variant").reset_index(drop=True)
combined

,country,country_code,year_week,new_cases,population,B.1.1.529,B.1.1.7,B.1.617.2
0,Austria,AT,2020-40,5597,8901064,0.000000,NaN,NaN
1,Austria,AT,2020-40,5597,8901064,NaN,0.0,NaN
2,Austria,AT,2020-40,5597,8901064,NaN,NaN,0.000000
3,Austria,AT,2020-41,7486,8901064,0.000000,NaN,NaN
4,Austria,AT,2020-41,7486,8901064,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...
6835,Slovakia,SK,2022-09,75031,5457873,NaN,NaN,2.749459
6836,Slovakia,SK,2022-09,75031,5457873,1371.980220,NaN,NaN
6837,Slovakia,SK,2022-10,71256,5457873,NaN,0.0,NaN
6838,Slovakia,SK,2022-10,71256,5457873,NaN,NaN,0.000000
6839,Slovakia,SK,2022-10,71256,5457873,1305.563541,NaN,NaN

In [12]:
data = []
for idx, row in combined.iterrows():
    row_list = []
    if idx > 1:
        prev = (idx - 1)
        if row["year_week"] == list(combined.loc[combined.index == prev]["year_week"])[0]:
            if pd.isna(row["B.1.1.529"]):
                row["B.1.1.529"] = list(combined.loc[combined.index == prev]["B.1.1.529"])[0]
            if pd.isna(row["B.1.1.7"]):
                row["B.1.1.7"] = list(combined.loc[combined.index == prev]["B.1.1.7"])[0]
            if pd.isna(row["B.1.617.2"]):
                row["B.1.617.2"] = list(combined.loc[combined.index == prev]["B.1.617.2"])[0]
        if row["year_week"] == list(combined.loc[combined.index == prev - 1]["year_week"])[0]:
            if pd.isna(row["B.1.1.529"]):
                row["B.1.1.529"] = list(combined.loc[combined.index == prev - 1]["B.1.1.529"])[0]
            if pd.isna(row["B.1.1.7"]):
                row["B.1.1.7"] = list(combined.loc[combined.index == prev - 1]["B.1.1.7"])[0]
            if pd.isna(row["B.1.617.2"]):
                row["B.1.617.2"] = list(combined.loc[combined.index == prev - 1]["B.1.617.2"])[0]
                
        row_list.append(row["country"]) 
        row_list.append(row["country_code"])
        row_list.append(row["year_week"])
        row_list.append(row["new_cases"])
        row_list.append(row["B.1.1.7"])
        row_list.append(row["B.1.617.2"])
        row_list.append(row["B.1.1.529"])
        row_list.append(row["population"])
        data.append(row_list)

In [13]:
updated_df = pd.DataFrame(data,columns=["Country","Country_Code","Year_Week","New_Cases","Alpha","Delta","Omicron",
                                       "Population"])
updated_df = updated_df.dropna(thresh=6)
updated_df = updated_df.drop_duplicates(subset=['Country_Code', 'Year_Week'], keep='last')
updated_df = updated_df.set_index("Country")
updated_df = updated_df.fillna(0)
updated_df

,Country_Code,Year_Week,New_Cases,Alpha,Delta,Omicron,Population
Country,,,,,,,
Austria,AT,2020-40,5597,0.0,0.000000,0.000000,8901064
Austria,AT,2020-41,7486,0.0,0.000000,0.000000,8901064
Austria,AT,2020-42,9903,0.0,0.000000,0.000000,8901064
Austria,AT,2020-43,18273,0.0,0.000000,0.000000,8901064
Austria,AT,2020-44,31613,0.0,0.000000,0.000000,8901064
...,...,...,...,...,...,...,...
Slovakia,SK,2022-06,137286,0.0,271.660553,2238.684191,5457873
Slovakia,SK,2022-07,123480,0.0,4.524840,2257.894971,5457873
Slovakia,SK,2022-08,95640,0.0,0.000000,1752.330990,5457873
Slovakia,SK,2022-09,75031,0.0,2.749459,1371.980220,5457873
Slovakia,SK,2022-10,71256,0.0,0.000000,1305.563541,5457873

In [14]:
updated_df.to_csv("tidy_variant_data.tsv", sep="\t")